name: EpubToAudiobook
options:
  bundleIdPrefix: com.example
  createIntermediateGroups: true
  generateEmptyDirectories: true
packages:
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    from: 0.9.0
  SWXMLHash:
    url: https://github.com/drmohundro/SWXMLHash.git
    from: 7.0.0
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup.git
    from: 2.7.0
targets:
  EpubToAudiobook:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - path: App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.EpubToAudiobook
        INFOPLIST_FILE: App/Resources/Info.plist
        SWIFT_VERSION: 5.9
    dependencies:
      - package: ZIPFoundation
      - package: SWXMLHash
      - package: SwiftSoup
  EpubToAudiobookTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/AppTests
    dependencies:
      - target: EpubToAudiobook
